package sandrone.command;

import sandrone.AiHelper;
import sandrone.AppState;
import sandrone.parser.Pulonia;
import sandrone.ui.SandroneUi;
import sandrone.util.Messages;
import sandrone.util.Storage;

public class AiQueryCommand extends Command {

    private final String userPrompt;
    private final AiHelper aiHelper;

    public AiQueryCommand(String userPrompt) {
        this.userPrompt = userPrompt;
        this.aiHelper = new AiHelper();
    }

    @Override
    public String execute(AppState appState, SandroneUi ui, Storage storage) {

        try {
            return commandAiToPerform(userPrompt, aiHelper, appState, ui, storage);
        } catch (Exception e) {
            return "Error querying AI helper: " + e.getMessage();
        }
    }

    String commandAiToPerform(String userPrompt, AiHelper aiHelper, AppState appState, SandroneUi ui, Storage storage) {
        String systemPrompt = "You are an assistant for a CLI task management app. Based on the user's request, generate a valid command that the app understands."
                + "Only respond with the command, nothing else.\n\n"
                + "Available commands:\n"
                + "1. todo <description> - Adds a todo task.\n"
                + "2. deadline <description> /by <yyyy-MM-dd> - Adds a task with a deadline.\n"
                + "3. event <description> /from <yyyy-MM-dd HHmm> /to <yyyy-MM-dd HHmm> - Adds an event task.\n"
                + "4. list - Lists all tasks.\n"
                + "5. mark <task_number> - Marks a task as done.\n"
                + "6. unmark <task_number> - Marks a task as not done."
                + "6. delete <task_number> - Deletes a task.\n"
                + "7. help - Shows the help message."
                + "8. find <keyword> - Searches for tasks that contain the specified keyword in their description."
                + "9. recur <todo/deadline/event> - Prefixes a task to make it repeat weekly."
                + "10. drecur <todo/deadline/event> - Stops a task from recurring by deleting the recurring task."
                + "11. sync - Calls recurring task generators to create task instances.";
        String generatedCommandText = aiHelper.getAiResponse(systemPrompt, userPrompt).aiMessage().text().trim();

        try {
            // 1. Feed the AI string directly back into your existing parsing/execution chain
            Command dynamicCommand = Pulonia.parseCommand(generatedCommandText);

            // 2. Execute the inner command using the current state
            String executionResult = dynamicCommand.execute(appState, ui, storage);

            // 3. Return both the acknowledgment and the actual result of the task
            return "AI generated command: \"" + generatedCommandText + "\"\n" + executionResult;

        } catch (Exception e) {
            // Catches invalid commands generated by the AI or parsing errors
            return "Sorry, I couldn't interpret or execute the AI's response: " + e.getMessage();
        }
    }
    
}
